modules/adminDashboardApp/urls.py
from django.urls import path
from modules.adminDashboardApp.views import EmployeeProfileList, EmployeeProfileDetail
from modules.adminDashboardApp.views import CompaneyCreateList, CompanyRetrieveUpdateDestroy
from modules.adminDashboardApp.views import DepartmentCreateList, DepartmentRetrieveUpdateDestroy
from modules.adminDashboardApp.views import JoinLetterAPIView, ConvertPdfAPIView
app_name='adminDashboardApp'
urlpatterns = [
    path('employee/create_list/', EmployeeProfileList.as_view(), name='create_list'),
    path('employee/retrieve_update_estroy/<slug:slug>/', EmployeeProfileDetail.as_view(), name='retrieve_update_estroy'),
    path('company/create_list/', CompaneyCreateList.as_view()),
    path('company/retrieve_update_destroy/<slug:slug>/', CompanyRetrieveUpdateDestroy.as_view()),
    path('department/create_list/', DepartmentCreateList.as_view(), name='department_create_list'),
    path('department/retrieve_update_destroy/<slug:slug>/', DepartmentRetrieveUpdateDestroy.as_view(), name='department_retrieve_update_destroy'),
    path('join-letter/', JoinLetterAPIView.as_view(), name='join_letter'),
    path('convert_pdf/', ConvertPdfAPIView.as_view(), name='convert_pdf')
]

organization/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="JobPortal API",
      default_version='v1',
      description="This is an API for a JobPortal Application",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminDashboardApp/', include('modules.adminDashboardApp.urls', namespace= "admin_dashboard")),
    path('jobPortalApp/', include('modules.jobPortalApp.urls', namespace= "job_portal")),
    path('swagger<str:format>.json/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

templates/joiningLetter/join.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/joining.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
  <div class="container">
    <div class="upper-content">
      <img src="{% static 'images/webkrone.png' %}" alt="" />
      <p class="logo-p">Webkrone Technology Pvt. Ltd.</p>
      <label>Date:</label>
      <input type="text" class="logo-date-input" name="date" />
    </div>
  </div>
  <br />
  <div class="container address-content">
    <div class="office-content">
      <p class="office-p">
        To,<br />Webkrone Technology Pvt. Ltd. <br />
        Module E, 3rd Floor, <br />
        Salt Lake Incubation Center, <br />
        XI-8/2, Block - EP, Salt Lake City Sector 5, <br />
        Kolkata - 700091, <br />
        Email: contact@webkrone.com
      </p>
    </div>
  </div>
  <div class="container form-content">
    <h4 class="text-center"><u>Sub:- Joining Letter</u></h4>
    <form method="post" action="{% url 'admin_dashboard:convert_pdf' %}">
      {% csrf_token %}
      <p class="form-p">
        Dear Sir, <br />
        I <input type="text" class="form-data" name="emp_name" />, have joined
        Webkrone Technology Pvt. Ltd., today i.e,
        <input type="text" class="form-data" name="date" /> <br />
        <br />
        as <input type="text" class="form-data" name="position" /> at
        <input type="text" class="form-data" name="location" /> (location) and
        have No Objection from my previous <br />
        <br />
        Company <input type="text" class="form-data" name="pre_company" />and
        my Parents / Spouse / Local Guardian - Mr / Mrs / Ms
        <input type="text" class="form-data-1" name="guardian" />.
        <br /><br /><br />
        Thanking You, <br /><br />
        Yours Sincerely, <br />
        <input type="text" class="sign" name="emp_name" />
      </p>
      <br />
      <button class="btn btn-success">Export_to_pdf</button>
    </form>
  </div>
  <br /><br /><br />
  <footer>
    <p class="footer-p text-center">
      <span id="company_name"> Webkrone Technology Pvt. Ltd., </span><br />
      Module E, 3rd Floor, Salt Lake Incubation Center, XI-8/2, Block - EP,
      Salt Lake City Sector 5, <br />Kolkata - 700091, Email:
      contact@webkrone.com
    </p>
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/joiningLetter/pdf_change.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Joining Letter</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <style>
      img {
        width: 162px;
        height: 40px;
        margin-top: 10%;
      }

      .upper-content {
        position: absolute;
        right: 3%;
      }

      .logo-p {
        margin-top: 8px;
      }

      .logo-date-input {
        border: 0;
        border-bottom: 1px solid black;
        outline: 0;
        width: 70%;
        margin-top: 2%;
      }

      .office-content {
        margin-top: 20%;
      }

      .form-data {
        border: 0;
        border-bottom: 1px solid black;
        outline: 0;
        width: 30%;
      }

      .sign {
        border: 0;
        border-bottom: 1px solid black;
        outline: 0;
        width: 15%;
      }

      /* .form-p {
        padding-left: 5%;
      } */

      span {
        font-size: 18px;
        font-weight: 700;
      }

      .form-data-1 {
        border: 0;
        border-bottom: 1px solid black;
        outline: 0;
        width: 24%;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="upper-content">
        <img src="{{ image_path }}" alt="" />
        <p class="logo-p">Webkrone Technology Pvt. Ltd.</p>
        <label>Date:</label>
        {{ date }}
      </div>
    </div>
    <br />
    <div class="container address-content">
      <div class="office-content">
        <p class="office-p">
          To,<br />Webkrone Technology Pvt. Ltd. <br />
          Module E, 3rd Floor, <br />
          Salt Lake Incubation Center, <br />
          XI-8/2, Block - EP, Salt Lake City Sector 5, <br />
          Kolkata - 700091, <br />
          Email: contact@webkrone.com
        </p>
      </div>
    </div>
    <div class="container form-content">
      <h4 style="text-align: Center"><u>Sub:- Joining Letter</u></h4>
        <p class="form-p">
          Dear Sir, <br />
          I {{ emp_name }}, have joined Webkrone Technology Pvt. Ltd., today
          i.e, {{ date }}
          <br />
          as {{ position }} at {{ location }} (location) and have No Objection
          from my previous
          <br />
          Company {{ pre_company }} and my Parents / Spouse / Local Guardian -
          Mr / Mrs / Ms {{ guardian }}. <br /><br /><br />
          Thanking You, <br /><br />
          Yours Sincerely, <br />
          {{ emp_name }}
        </p>
    </div>
    <br /><br /><br />
    <footer>
      <p style="text-align: Center">
        <span> Webkrone Technology Pvt. Ltd., </span><br />
        Module E, 3rd Floor, Salt Lake Incubation Center, XI-8/2, Block - EP,
        Salt Lake City Sector 5, <br />Kolkata - 700091, Email:
        contact@webkrone.com
      </p>
    </footer>
  </body>
</html>